[tools]
go = "1.25.6"
"go:connectrpc.com/connect/cmd/protoc-gen-connect-go" = "v1.11.0"
"go:github.com/bufbuild/buf/cmd/buf" = "v1.62.1"
"go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "4.19.0", tags = "postgres" }
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "v1.30.0"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "v1.31.0"
node = "23.1.0"
"npm:@bufbuild/protoc-gen-es" = "1.2.0"
"npm:@bufbuild/protoc-gen-connect-web" = "0.9.0"
pnpm = "9.12.3"
python = "3.8.16"
"pipx" = "1.7.1"
"pipx:sqlfluff" = "2.3.2"

[env]
CGO_CFLAGS = "-DHAVE_STRCHRNUL"
