[tools]
go = "1.23.0"
"go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "4.19.0", tags = "postgres" }
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "1.27.0"
node = "23.1.0"
pnpm = "9.12.3"
